export const STUDENT_DETAIL_START = "STUDENT_DETAIL_START";
export const STUDENT_DETAIL_SUCCESS = "STUDENT_DETAIL_SUCCESS";
export const STUDENT_DETAIL_FAILURE = "STUDENT_DETAIL_FAILURE";

export const STUDENT_CALENDER_START = "STUDENT_CALENDER_START";
export const STUDENT_CALENDER_SUCCESS = "STUDENT_CALENDER_SUCCESS";
export const STUDENT_CALENDER_FAILURE = "STUDENT_CALENDER_FAILURE";

export const GET_CREDIT_START = "GET_CREDIT_START";
export const GET_CREDIT_SUCCESS = "GET_CREDIT_SUCCESS";
export const GET_CREDIT_FAILURE = "GET_CREDIT_FAILURE";
